### PR TITLE
Add 'Back' button in Questions screen

### LINKED ISSUE #15: [FEATURE] Add "Back" button in Questions page
### Description

In Questions page, adding "Back" button to navigate to the topics modal will provide users to change a topic for the next set. Currently user have to refresh even after completing the quiz for choosing a different topic in the next game.

### Screenshots

Screenshot 2022-08-13 at 10 49 37 PM
Screenshot 2022-08-13 at 10 49 59 PM

### PR DESCRIPTION
**Pull request by kabilansakthivelu**
### Related Issue/Addition to code
- "Back" button in Questions screen for navigating back to topics section

### 👨‍💻 What's being changed:

- Added "Back" button on the Questions screen.
- On clicking the button, topics modal will be displayed where users can pick their favorite.

### Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Original | Updated
:----------------------:|:-----------:
 Screenshot 2022-08-13 at 10 49 37 PM  | Screenshot 2022-08-13 at 11 23 09 PM

Original | Updated
:----------------------:|:-----------:
Screenshot 2022-08-13 at 11 27 16 PM  | Screenshot 2022-08-13 at 11 27 36 PM

### CODE REVIEW

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Great work @kabilansakthivelu🚀

It works great! But I have one suggestion, what if you put the back button at the top rather than at the bottom?
image

**Comment by kabilansakthivelu** [comment]
Hi @Dharmik48, made changes to display "Back" button at the top of the page.

Please find the attached screenshot for your reference. Thank you

Screenshot 2022-08-14 at 3 08 26 PM

**Comment by Dharmik48** [comment]
Yea, this one looks very good! But I think it feels a bit too large for a _back_ button, maybe we should keep the colors the same but reduce the `font-size` and `padding` to match the `font-size` and `padding` of the choices of questions.

What do you think about this?

**Comment by kabilansakthivelu** [comment]
> Yea, this one looks very good! But I think it feels a bit too large for a _back_ button, maybe we should keep the colors the same but reduce the `font-size` and `padding` to match the `font-size` and `padding` of the choices of questions.
> 
> What do you think about this?

Sure. it would be nice to match the same style as applied for choices.

**Comment by kabilansakthivelu** [comment]
Hi @Dharmik48, please have a look at the attached screenshot. 

Kindly let me know if you need any changes to be made. Thank you

Screenshot 2022-08-14 at 3 30 00 PM

**Review by Dharmik48 — APPROVED** [review]
Awesome🎉

Let's merge it! Thanks a lot for contributing😊

**Pull request merged**
